### PR TITLE
Fix derivatives in CALPHADConcSolverBinary3Ph2Sl

### PR DESCRIPTION
**Pull request by jeanlucf22**

### CODE REVIEW

**Comment by jeanlucf22** [comment]
Does not matter for AlCu since q=1, but incorrect/inconsistent in my opinion

**Comment by stvdwtt** [comment]
I could have made an error, but I think that `q` should be there.

From [here](http://www.opencalphad.com/databases/CGNA18499ENC_001.pdf) the ideal mixing term is defined as:
image

The `q` there becomes the `q` that goes as part of the `RT` coefficient:
https://github.com/ORNL/Thermo4PFM/blob/dc8be8caf06d670004b79a2b68904247f59fe28f/src/CALPHADFreeEnergyFunctionsBinary3Ph2Sl.cc#L155

Then that `q` makes it to the RHS.

Am I missing something? There are enough variable transforms, etc. that I wouldn't be surprised if I was.

**Comment by jeanlucf22** [comment]
Oh, I see. I had missed that q. I would actually put it in front of the function to make it more clear, although it is equivalent. We may need some comments so that we don't question these expressions every time we look at them ;-)

**Comment by stvdwtt** [comment]
Agreed on the comments :)

**Pull request closed without merging**
